#!/usr/bin/env python
import rospy
from geometry_msgs.msg import TwistStamped
import numpy as np
import time
import signal
import sys

def signal_handler(signal, frame):
    sys.exit(0)

if __name__ == '__main__':
    rospy.init_node('panda_velocity_control_test')

    pub = rospy.Publisher('/panda/cart_velocity', TwistStamped, queue_size=1)
    signal.signal(signal.SIGINT, signal_handler)

    angle = 0
    alpha = .1
    while True:
        msg = TwistStamped()
        msg.header.stamp = rospy.Time.now()+rospy.Duration.from_sec(.050)
        msg.twist.linear.x = np.sin(angle)*alpha
        msg.twist.linear.y = np.sin(angle)*alpha
        msg.twist.linear.z = np.sin(angle)*alpha
        msg.twist.angular.x = np.cos(angle)*alpha
        msg.twist.angular.y = np.cos(angle)*alpha
        msg.twist.angular.z = np.cos(angle)*alpha
        pub.publish(msg)
        rospy.sleep(0.001)
        angle += 0.002