#!/usr/bin/env python
import rospy
from panda_ros_msgs.msg import HybridPose
import numpy as np
import time

if __name__ == '__main__':
    rospy.init_node('panda_hybrid_control_test')

    pub = rospy.Publisher('/panda/hybrid_pose', HybridPose, queue_size=1)
    rospy.sleep(0.5)


    start = time.time()
    while time.time() - start < 5:
        t = time.time() - start
        z = 0.3 - 0.28 * (t / 5)
        p = HybridPose()
        p.pose.position.x = 0.5
        p.pose.position.y = 0
        p.pose.position.z = z
        p.pose.orientation.w = 1

        p.sel_vector = [1,1,1,0,0,0]
        pub.publish(p)
        rospy.sleep(0.001)
    
    start = time.time()
    while time.time() - start < 5:
        t = time.time() - start
        y = 0.1 * (t / 5)
        p = HybridPose()
        p.pose.position.x = 0.5
        p.pose.position.y = y
        p.pose.position.z = z
        p.pose.orientation.w = 1

        p.sel_vector = [1,1,0,0,0,0]
        p.wrench.force.z = 3

        pub.publish(p)
        rospy.sleep(0.001)


