#!/usr/bin/env python
import rospy
from panda_ros_msgs.msg import HybridPose
import numpy as np
from scipy.spatial.transform import Rotation

if __name__ == '__main__':
    rospy.init_node('panda_hybrid_control_test')

    pub = rospy.Publisher('/panda/hybrid_pose', HybridPose, queue_size=1)
    rospy.sleep(0.5)

    rate = 1337
    dtheta = 0.004 * 500 / rate

    r = rospy.Rate(rate)


    while True:
        for theta in np.arange(0, 2 * np.pi, dtheta):
            p = HybridPose()
            
            p.pose.position.x = 0.05*np.sin(theta) + 0.42
            p.pose.position.y = 0.05*np.sin(theta) + .1
            p.pose.position.z = 0.05*np.sin(theta) + 0.25

            p.sel_vector=[1,1,1,0,0,0]
            
            R = Rotation.from_euler('XYZ', [0.1*np.sin(theta), 0.1*np.sin(theta), 0.1*np.sin(theta)])
            q = R.as_quat()
            p.pose.orientation.x = q[0]
            p.pose.orientation.y = q[1]
            p.pose.orientation.z = q[2]
            p.pose.orientation.w = q[3]

            pub.publish(p)
            r.sleep()


