#!/bin/bash

# Build Panda Controller
cd PandaController
rm -r build
mkdir build
cd build
cmake ..
make install
cd ../../..


# Build other ROS packages
catkin build panda_ros --no-notify
catkin build panda_ros_msgs --no-notify
