#!/bin/bash

# Build Actuation
cd Actuation
source compileActuation
cd ..

# Build Execution
cd Execution
source compileExecution
cd ..

# Build ULI Config
catkin build uli_config --no-notify

# Build Interface
catkin build uli_interface --no-notify
cd Interface/react
npm install
cd ../..
