#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import PointCloud2, Image, CompressedImage
import numpy as np
import sys
import rospkg
from cv_bridge import CvBridge, CvBridgeError
import cv2

def sender():
    rospy.init_node('pc_sender')
    print("reading")
    msg = PointCloud2()
    rospack = rospkg.RosPack()
    path = rospack.get_path('uli_interface')+'/saved_msgs/pc.txt'
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    #msg.header.frame_id = 'static_camera_link'
    msg.header.stamp = rospy.Time.now()
    msg.header.frame_id = "camera_visor"
    pub = rospy.Publisher("/cloud2",PointCloud2, queue_size =1, latch = True)
    pub.publish(msg)
    # path = rospack.get_path('uli_interface')+'/saved_msgs/depth.jpeg'
    # msg = CompressedImage()
    # bridge = CvBridge()
    # with open(path, 'rb') as infile:
    #     cv2_img = cv2.imread(path)
        #msg.deserialize(infile.read())
        # msg = bridge.
    # pub = rospy.Publisher("/depth_to_rgb/image_raw/compressed",CompressedImage, queue_size =1, latch = True)
    # pub.publish(msg)
    rospy.spin()

if __name__ == '__main__':
    sender()