#!/usr/bin/env python
import rospy
from sensor_msgs.msg import PointCloud2, CameraInfo, CompressedImage
from std_msgs.msg import String,Float64
import numpy as np
import sys
import rospkg
import cv2
from cv_bridge import CvBridge, CvBridgeError
import sys
import signal

bridge = CvBridge()

def signal_handler(signal, frame):
    sys.exit()

def sender():
    rospy.init_node('img_sender')
    print("reading")
    suffix = "_flat"
    
    rospack = rospkg.RosPack()

    path = rospack.get_path('uli_interface')+'/saved_msgs/depth'+suffix+'.txt'
    msg = CompressedImage()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub1 = rospy.Publisher("/k4a/depth_to_rgb/image_raw/compressed",CompressedImage, queue_size =1, latch = True)
    pub1.publish(msg)

    path = rospack.get_path('uli_interface')+'/saved_msgs/rgb'+suffix+'.txt'
    msg = CompressedImage()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub2 = rospy.Publisher("/k4a/rgb/image_raw/compressed",CompressedImage, queue_size =1, latch = True)
    pub2.publish(msg)

    path = rospack.get_path('uli_interface')+'/saved_msgs/info'+suffix+'.txt'
    msg = CameraInfo()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub3 = rospy.Publisher("/k4a/depth_to_rgb/camera_info",CameraInfo, queue_size =1, latch = True)
    pub3.publish(msg)

    path = rospack.get_path('uli_interface')+'/saved_msgs/cloud'+suffix+'.txt'
    msg = PointCloud2()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    msg.header.stamp = rospy.Time.now()
    pub4 = rospy.Publisher("/k4a/points2",PointCloud2, queue_size =1, latch = True)
    pub4.publish(msg)
    print(msg.header)
    print("published all")
    pub5 = rospy.Publisher("/ui/robot_state",String, queue_size =1, latch = True)
    pub6 = rospy.Publisher("/panda/sandpaper_health",Float64, queue_size =1, latch = True)

    rate = rospy.Rate(1.)
    signal.signal(signal.SIGINT, signal_handler)
    while not rospy.is_shutdown():
        pub5.publish("green")
        pub6.publish(1.)    
        rate.sleep()

if __name__ == '__main__':
    sender()