#!/usr/bin/env python
import rospy
from sensor_msgs.msg import PointCloud2, CameraInfo, CompressedImage
import numpy as np
import sys
import rospkg
import cv2
from cv_bridge import CvBridge, CvBridgeError


bridge = CvBridge()

def sender():
    rospy.init_node('img_sender')
    print("reading")
    
    rospack = rospkg.RosPack()

    path = rospack.get_path('uli_interface')+'/saved_msgs/depth.txt'
    msg = CompressedImage()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub1 = rospy.Publisher("/k4a/depth_to_rgb/image_raw/compressed",CompressedImage, queue_size =1, latch = True)
    pub1.publish(msg)

    path = rospack.get_path('uli_interface')+'/saved_msgs/rgb.txt'
    msg = CompressedImage()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub2 = rospy.Publisher("/k4a/rgb/image_raw/compressed",CompressedImage, queue_size =1, latch = True)
    pub2.publish(msg)

    path = rospack.get_path('uli_interface')+'/saved_msgs/info.txt'
    msg = CameraInfo()
    with open(path, 'rb') as infile:
        msg.deserialize(infile.read())
    pub3 = rospy.Publisher("/k4a/depth_to_rgb/camera_info",CameraInfo, queue_size =1, latch = True)
    pub3.publish(msg)

    rospy.spin()

if __name__ == '__main__':
    sender()