#!/bin/bash

# Build other ROS packages
catkin build actuation_group --no-notify
catkin build panda_sim --no-notify
catkin build controlled_valve --no-notify
catkin build ft_sensor --no-notify
catkin build kinect_ros --no-notify
catkin build hybrid_controller --no-notify
